config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers=>{registrations:"registrations"}
  resources :events do
   put :upvote
   
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "events#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events 

end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
def attend
    @event.attendees << current_user
    @event.save
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: [:index,:show]
  # GET /events or /events.json
  def index
    @events = Event.all
    if user_signed_in?
    @spic_event=current_user.events
    end
    @event = Event.new
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  def upvote
    @event = Event.find(params[:id])
    @event.increment! :votes
  end
  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title,:location, :disc,:date,:price)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    def sign_up_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation)
    end
    def account_update_params 
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation,:current_password)
    end
    end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_gravatar(user)
        gravatar_id = Digest::MD5::hexdigest(user.eamil.downcase)
        gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name)
      end
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/attends/_attendee.html.erb
<div class="card">
<div class="card-body">
Hello

</div>
</div>

app/views/events/_allevents.html.erb
<div class="d-flex flex-wrap mx-lg-5 my-5 ">
<% @events.each do |event| %>

    <div class="mx-2 my-3 card"style="width:220px">
        <article class="card-body">
            <div class="media-left">
                <figure class="image is-64x64">
                    <%# <%=gravatar_image_tag(event.user.email,size:64,alt:event.user.name) %>
                <%= image_tag 'default/tree.jpg', class:"img-fluid rounded mx-auto d-block"%>

                </figure>
            </div>
            <div class="media-content">
                <div class="content" style="margin-bottom:40px">
                   <span> <strong><%= event.title %></strong> at <strong><%= event.location%></strong></span>
                    <br/>
                    <strong>Date: <%= event.date%></strong><br/>
                    <strong>Creater: <%= event.user.name%></strong><br/>
                    <span><%=event.disc %></span>
                    
                    <p>Price:<%= event.price%></p><br/>                    
                </div>
                <%if user_signed_in? %>
                <div class="level" >
                    <div class="level-left is-mobile">
                        <%= link_to event, class: "level-item icons" do %>
                        
                             <span class="icon mx-1">
                                <i class="bi bi-link"aria-hidden="true" style="width:10px ;margin-bottom:10px"></i></span>
                                <%end%>                     
                                 <%# <%= link_to attend_event_path(event), method: :post, confirm: 'really?' do%>
                               <%# <%= link_to 'like', event_upvote_path(event), method: :put ,class:"mx-1"%>
                               <i class="bi bi-bookmark mx-1" ></i>                                
                    </div>                                
                </div>          
                <%end%>         
            </div>
        </article>
    </div>

    <%end%>
    </div>

app/views/events/_event.html.erb
<div class="card ">
<%if user_signed_in?%>
    <article class="card-body">
        <p class="fs-1" >Create Event</p>
        <div class="media-content">
            <%= render "events/form" %>
        </div>
    </article>
<% end %>
</div>

app/views/events/_eventbyuser.html.erb
<div class="card">
<div class="card-body ">
<h2>Events Created</h2>
<div class="my-3 scroll">

<% @spic_event.each do |event| %>
<div class="card my-3">
<div class="card-body">
<h4 class="my-2 "><%=event.title%></h4>
<%= link_to edit_event_path(event), class: "icons mx-3" do %>
<span class="icon"><i class="bi bi-pencil-square"></i></span>
<%end%>
<%= link_to event,method: :delete,data: {confirm:"Are you sure you want to delete this tweet?"},class:"icons" do %>
<span class="icon"><i class="bi bi-trash3"></i></span>
<%end%>
</div>
</div>
<%end%>
</div></div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  

<%# <%=f.error_notification%>
<div class="field">
<div class="container">
<%= f.input :title,label:"Event title", input_html:{class:"textarea my-1"},wrapper: false,lable_html:{class:"label"},placeholder:"Compose a new Event...",autofocus:true%>
<%= f.input :location,label:"Event location", input_html:{class:"textarea my-1"},wrapper: false,lable_html:{class:"label"}%>
<%= f.input :disc,label:"Event Discription", input_html:{class:"text"},wrapper: false,lable_html:{class:"label"}%>

<%= f.input :date,label:"Event Date", input_html:{class:"date"},wrapper: false,lable_html:{class:"date"}%>
<%= f.input :price,label:"Price it", input_html:{class:"textarea my-1"},wrapper: false,lable_html:{class:"label"},placeholder:"Add a Price"%>
</div>
</div>
<%= f.button :submit , class:"btn btn-info my-3" %>
<%end%>

app/views/events/_profile.html.erb
<div class="card is-one-quarter" style="width:250px;max-higeht:500px">
    <div class="card-body ">
        <h3 class="card-title">Creater</h3>
        <div class="panel-block">
            <article class="media">
                <div class="media-left d-flex  my-3">
                    <figure class="image is64x64 mx-4">
                    <%# <%=gravatar_image_tag(current_user.email,alt:current_user.name) %>
                    <%= image_tag 'default/user.png',size:64 %>
                    </figure>   
                        <p>
                            <strong><%=current_user.name%></strong><br/>
                        <small><%=current_user.username%></small></p>
                    </div>
            </article>
        </div>
        <div class="panel-block ">
            <div class="d-flex justify-content-around">
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading"></p>
                        <p class="title is-6">
                            Events Created : <b><%=current_user.events.count%></b>
                        </p>
                        <p class="heading"></p>
                        <p class="title is-6">
                            Events Attend : <b><%=current_user.events.count%></b>
                        </p>
                    </div>
                </div>
               
                </div>
            </div>
        </div>
    </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<section class="section my-5">
<div class="container d-flex justify-content-center ">
<%if user_signed_in?%>
<div class="d-flex justify-content-evenly ">
<span><%= render "profile"%> 
</span>
<span><%=render "eventbyuser"%>
</span>
<span><%= render 'event'%>
</span>
<%# <%=render "attends/attendee"%>
<%end%>
</div>
<hr style="width:90%;text-align:center;margin-left:70px">
<h2 class="mx-5">All Events</h2>
<%= render 'allevents'%>
</div>
</section>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
  </head>

  <body>
<%if flash[:notice] %>
    <div class="notification is-primary global-notification">
    <p class="notice"><%=notice%></p>
    </div>
    <%end%>
    <%if flash[:alert]%>
    <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
    </div><%end%>
       <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%=link_to "Events",root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%=link_to "Profile",root_path,class:"nav-link" %>
        </li>
      </ul>
     <p class="control mx-2">
    <%= link_to "New Event",root_path, class: "btn btn-info btn-inverted"%>
    </p>
    <%if user_signed_in?%>
    <p class="control mx-2">
    <%= link_to current_user.name,edit_user_registration_path,class:"btn btn-info"%>
    </p>
    <p class="control mx-2" >
    <%= link_to "Logout",destroy_user_session_path,method: :delete,class:"btn btn-info"%>
    </p>
    <%else%>
    <p class="control mx-2">
    <%=link_to "Sign In",new_user_session_path,class:"btn btn-info"%>
    </p>
    <p class="control mx-2">
    <%= link_to "Sing Up",new_user_registration_path,class:"btn btn-info"%>
    </p>
    <%end%>
    </div>
  </div>
</nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

  </body>
</html>